version: '3.8'

services:
  # 数据库服务
  # 先单独构建
  # realworld-db:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.db
  #   ports:
  #     - "5433:5432"
  #   restart: always

  # server 服务
  realworld-server:
    build:
      context: .
      args:
        DATABASE_URL: postgres://user0:123456@115.120.251.181:5433/realworld
        JWT_SECRET: WmFqZ2x1c3RlckB+KiQjJV4mKigpX3s=
        NODE_ENV: production
        PORT: 3000
    image: realworld-server  # 自定义镜像名称
    ports:
      - "3000:3000"
    restart: always

  # web 服务
  realworld-web:
    build:
      # 修改 context 为 /web 项目所在目录
      context: ../react-redux-realworld-example-app
    image: realworld-web  # 自定义镜像名称
    ports:
      - "4100:80"
    restart: always
    depends_on:
      - realworld-server
