version: '3.8'

services:
  # 数据库服务
  realworld-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5433:5432"
    # 新增健康检查
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user0 -d realworld"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # server 服务
  realworld-server:
    build:
      context: .
      args:
        DATABASE_URL: postgres://user0:123456@115.120.251.181:5433/realworld
        JWT_SECRET: WmFqZ2x1c3RlckB+KiQjJV4mKigpX3s=
        NODE_ENV: production
        PORT: 3000
    ports:
      - "3000:3000"
    restart: on-failure:5
    depends_on:
      realworld-db:
        condition: service_healthy  # 关键依赖条件
    # 新增等待脚本
    command: 
      - sh
      - -c
      - |
        echo "等待数据库就绪..."
        while ! nc -z realworld-db 5432; do 
          sleep 2
        done
        pm2-runtime dist/api/main.js --log /app/logs/app.log

  # web 服务
  realworld-web:
    build:
      # 修改 context 为 /web 项目所在目录
      context: ../react-redux-realworld-example-app
    ports:
      - "4100:80"
    restart: always
    depends_on:
      - realworld-server
