-- 创建用户 (如果不存在)
CREATE USER user0 WITH PASSWORD '123456';

-- 创建数据库并设置所有者
CREATE DATABASE realworld WITH OWNER = user0 ENCODING = 'UTF8';

-- 授予用户所有权限
GRANT ALL PRIVILEGES ON DATABASE realworld TO user0;

-- 授予用户对public schema的所有权限
\c realworld
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO user0;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO user0;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO user0;
